name: ${project.name}
main: com.thekingelessar.assault.Assault
version: ${project.version}
author: TheKingElessar
softdepend: [ HolographicDisplays ]
depend: [ Citizens ]
commands:
  help:
    aliases: [ h, Help ]
    description: Explanation of commands.
    usage: |
      /help
  all:
    aliases: [ a, All ]
    description: Shows a chat message to all players in the game.
    usage: |
      /all <message>
  respawn:
    aliases: [ Respawn ]
    description: Kills you (in case you get stuck somewhere).
    usage: |
      /respawn
  forfeit:
    aliases: [ Forfeit, forfiet, Forfiet ]
    description: Toggles your vote to forfeit.
    usage: |
      /forfeit
  assault:
    description: Dev command. Kinda sus...
    usage: |
      /assault attack
      /assault coins <amount>
      /assault gp <amount>
