name: ${project.name}
main: com.thekingelessar.assault.Assault
version: ${project.version}
author: TheKingElessar
softdepend: [HolographicDisplays]
depend: [Citizens]
commands:
  assault:
    description: Utility commands.
    usage: |
      /assault start <map name>
      /assault attack
      /assault shop <building/attack>
      /assault create <map name> <auto-save> <world ID>
      /assault join <world ID>
      /assault close <world ID>