name: ${project.name}
main: com.thekingelessar.assault.Assault
version: ${project.version}
author: TheKingElessar
softdepend: [ HolographicDisplays ]
depend: [ Citizens ]
commands:
  respawn:
    description: Respawn, just in case you get trapped somewhere.
    usage: |
      /respawn
  all:
    description: Send chat messages to the entire game.
    usage: |
      /all <message>
  assault:
    description: Dev command.
    usage: |
      /assault attack